---
- name: Playbook for Nginx Servers
  become: true
  become_method: ansible.builtin.sudo
  debugger: never
  gather_facts: true
  hosts: all
  vars:
    enable_cloudinit: true
  roles:
    - nginx
    - clean
