---
- name: Debug ansible_os_family
  debug:
    msg: "ansible_os_family is {{ ansible_os_family }}"

- name: Debug platform
  debug:
    msg: "platform is {{ platform }}"

- name: "{{ clean_task_name }} - {{ platform }}"
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"
  when: ansible_os_family in ['Debian', 'RedHat'] and platform in ['vsphere-iso', 'vsphere-clone']
