- name: Install required system packages
  apt:
    pkg:
      - nginx
    state: latest
    update_cache: true

- name: Start and enable Nginx service
  systemd_service:
    name: nginx
    state: started
    enabled: yes
