---
- name: Debug ansible_os_family
  debug:
    msg: "ansible_os_family is {{ ansible_os_family }}"

- name: Debug platform
  debug:
    msg: "platform is {{ platform }}"

- name: "{{ users_task_name } - {{ platform }}"
  ansible.builtin.include_tasks: linux.yml
  when: ansible_os_family in ['Debian', 'RedHat'] or ansible_distribution == 'VMware Photon OS'
